// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sispark_api.Infrastructure.Data;

#nullable disable

namespace sispark_api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SisparkDbContext))]
    partial class SisparkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("sispark_api.Domain.Entities.Celda", b =>
                {
                    b.Property<int>("IdCelda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_celda");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCelda"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("codigo");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTipoVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_vehiculo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ubicacion");

                    b.HasKey("IdCelda");

                    b.ToTable("celdas", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)")
                        .HasColumnName("direccion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_actualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_creacion");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("Telefono")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("IdCliente");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Estado", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modulo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdEstado");

                    b.ToTable("estados", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Mensualidad", b =>
                {
                    b.Property<int>("IdMensualidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mensualidad");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdMensualidad"));

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("IdCeldaFija")
                        .HasColumnType("int")
                        .HasColumnName("id_celda_fija");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTarifa")
                        .HasColumnType("int")
                        .HasColumnName("id_tarifa");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdMensualidad");

                    b.HasIndex("IdCeldaFija");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTarifa");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("mensualidades", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.RegistroParqueo", b =>
                {
                    b.Property<int>("IdRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_registro");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRegistro"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ingreso");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_salida");

                    b.Property<int?>("IdCelda")
                        .HasColumnType("int")
                        .HasColumnName("id_celda");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTarifa")
                        .HasColumnType("int")
                        .HasColumnName("id_tarifa");

                    b.Property<int>("IdTipoServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_servicio");

                    b.Property<int>("IdUsuarioIngreso")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_ingreso");

                    b.Property<int?>("IdUsuarioSalida")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_salida");

                    b.Property<int>("IdVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    b.Property<int?>("MinutosConsumidos")
                        .HasColumnType("int")
                        .HasColumnName("minutos_consumidos");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("ValorCalculado")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_calculado");

                    b.Property<decimal>("ValorFinal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_final");

                    b.HasKey("IdRegistro");

                    b.HasIndex("IdCelda");

                    b.HasIndex("IdTarifa");

                    b.HasIndex("IdTipoServicio");

                    b.HasIndex("IdUsuarioIngreso");

                    b.HasIndex("IdUsuarioSalida");

                    b.HasIndex("IdVehiculo");

                    b.ToTable("registros_parqueo", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Tarifa", b =>
                {
                    b.Property<int>("IdTarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tarifa");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTarifa"));

                    b.Property<DateOnly?>("FechaFinVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fecha_fin_vigencia");

                    b.Property<DateOnly>("FechaInicioVigencia")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio_vigencia");

                    b.Property<int?>("FraccionMinutos")
                        .HasColumnType("int")
                        .HasColumnName("fraccion_minutos");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTipoServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_servicio");

                    b.Property<int>("IdTipoVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_vehiculo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor");

                    b.HasKey("IdTarifa");

                    b.HasIndex("IdTipoServicio");

                    b.HasIndex("IdTipoVehiculo");

                    b.ToTable("tarifas", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.TipoServicio", b =>
                {
                    b.Property<int>("IdTipoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_servicio");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoServicio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoServicio");

                    b.ToTable("tipos_servicio", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.TipoVehiculo", b =>
                {
                    b.Property<int>("IdTipoVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_vehiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdTipoVehiculo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoVehiculo");

                    b.ToTable("tipos_vehiculo", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultimo_acceso");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("IdVehiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vehiculo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdVehiculo"));

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("color");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int>("IdTipoVehiculo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_vehiculo");

                    b.Property<int?>("IdUsuarioActualizacion")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_actualizacion");

                    b.Property<int?>("IdUsuarioCreacion")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_creacion");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("marca");

                    b.Property<string>("Modelo")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modelo");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("observaciones");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("placa");

                    b.HasKey("IdVehiculo");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdTipoVehiculo");

                    b.ToTable("vehiculos", (string)null);
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Mensualidad", b =>
                {
                    b.HasOne("sispark_api.Domain.Entities.Celda", "CeldaFija")
                        .WithMany()
                        .HasForeignKey("IdCeldaFija");

                    b.HasOne("sispark_api.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sispark_api.Domain.Entities.Tarifa", "Tarifa")
                        .WithMany()
                        .HasForeignKey("IdTarifa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sispark_api.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CeldaFija");

                    b.Navigation("Cliente");

                    b.Navigation("Tarifa");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.RegistroParqueo", b =>
                {
                    b.HasOne("sispark_api.Domain.Entities.Celda", "Celda")
                        .WithMany()
                        .HasForeignKey("IdCelda");

                    b.HasOne("sispark_api.Domain.Entities.Tarifa", "Tarifa")
                        .WithMany()
                        .HasForeignKey("IdTarifa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sispark_api.Domain.Entities.TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("IdTipoServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sispark_api.Domain.Entities.Usuario", "UsuarioIngreso")
                        .WithMany()
                        .HasForeignKey("IdUsuarioIngreso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sispark_api.Domain.Entities.Usuario", "UsuarioSalida")
                        .WithMany()
                        .HasForeignKey("IdUsuarioSalida");

                    b.HasOne("sispark_api.Domain.Entities.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("IdVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Celda");

                    b.Navigation("Tarifa");

                    b.Navigation("TipoServicio");

                    b.Navigation("UsuarioIngreso");

                    b.Navigation("UsuarioSalida");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Tarifa", b =>
                {
                    b.HasOne("sispark_api.Domain.Entities.TipoServicio", "TipoServicio")
                        .WithMany()
                        .HasForeignKey("IdTipoServicio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sispark_api.Domain.Entities.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("IdTipoVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoServicio");

                    b.Navigation("TipoVehiculo");
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("sispark_api.Domain.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sispark_api.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("sispark_api.Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("sispark_api.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sispark_api.Domain.Entities.TipoVehiculo", "TipoVehiculo")
                        .WithMany()
                        .HasForeignKey("IdTipoVehiculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoVehiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
